### ISSUE TITLE
Logging?

### ISSUE THREAD

**Issue by carbureted** [csepulv/electron-with-create-react-app#4]
Hey, I'm fairly new with electron, so perhaps I'm missing something basic, but I noticed that console.log isn't working for anything on the electron-starter.js side of things. Is there an easy solution for this? The top stack overflow results weren't helpful, unfortunately.

**Comment by csepulv** [comment]
Unfortunately I don't know. I've never tried logging from the bootstrap script that loads the window. 

What do you need to log that isn't loggable elsewhere?

**Comment by sebassdc** [comment]
i think its beacause the server is constantly realoading and re-renders everything
im triying a simple ipc comunication and i dont know how to manually test it. How can i stop server and hot reloading?

**Comment by csepulv** [comment]
You probably need to [eject](https://github.com/facebookincubator/create-react-app#converting-to-a-custom-setup) your app, as the hot reloading it part of create-react-app.

**Comment by pikiaboy** [comment]
There is no logging from electron-starter.js because if you take a look at electron-wait-react.js, you can see that electron is actually being called from a child_process via exec. Because of this, the logging goes to a buffer that we have to provide in a callback. However, this gets really inefficient, as you'd have to close the electron app each time to check the logging. 

The best way I've found to fix this issue would be to run electron from a child_process.spawn(). This way, we can bind the stdout of the child_process and log it right away. 

`onst tryConnection = () => client.connect({port: port}, () => {
        client.end();
        if(!startedElectron) {
            console.log('starting electron');
            startedElectron = true;

            const { spawn } = require('child_process');
            const child = spawn('npm', ['run', 'electron']);
            child.stdout.on('data', (data) => {
                console.log(`child stdout: ${data}`);
              });
              
              child.stderr.on('data', (data) => {
                console.error(`child stderr: ${data}`);
              });
              child.on('exit', function (code, signal) {
                console.log('child process exited with ' +
                            `code ${code} and signal ${signal}`);
              });



            // const exec = require('child_process').exec;

            // exec('npm run electron',(error,stdout,stderr) => {
            //     console.log(stdout);
            // });
        }
    }
);`
